export const API_END_POINT = 'https://5ebb57e3f2cfeb001697cba9.mockapi.io/api/';

export const GET_ALL_USER = 'GET_ALL_USER';
export const GET_ALL_USER_SUCCESS = 'GET_ALL_USER_SUCCESS';
export const GET_ALL_USER_ERROR = 'GET_ALL_USER_ERROR';

export const ADD_USER = 'ADD_USER';
export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS';
export const ADD_USER_ERROR = 'ADD_USER_ERROR';

export const EDIT_USER = 'EDIT_USER';
export const EDIT_USER_SUCCESS = 'EDIT_USER_SUCCESS';
export const EDIT_USER_ERROR = 'EDIT_USER_ERROR';

export const DELETE_USER = 'DELETE_USER';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_ERROR = 'DELETE_USER_ERROR';

export const GET_ALL_QUESTION = 'GET_ALL_QUESTION';
export const GET_ALL_QUESTION_SUCCESS = 'GET_ALL_QUESTION_SUCCESS';
export const GET_ALL_QUESTION_ERROR = 'GET_ALL_QUESTION_ERROR';

export const ADD_QUESTION = 'ADD_QUESTION';
export const ADD_QUESTION_SUCCESS = 'ADD_QUESTION_SUCCESS';
export const ADD_QUESTION_ERROR = 'ADD_QUESTION_ERROR';

export const EDIT_QUESTION = 'EDIT_QUESTION';
export const EDIT_QUESTION_SUCCESS = 'EDIT_QUESTION_SUCCESS';
export const EDIT_QUESTION_ERROR = 'EDIT_QUESTION_ERROR';

export const DELETE_QUESTION = 'DELETE_QUESTION';
export const DELETE_QUESTION_SUCCESS = 'DELETE_QUESTION_SUCCESS';
export const DELETE_QUESTION_ERROR = 'DELETE_QUESTION_ERROR';

export const GET_ALL_EXAM = 'GET_ALL_EXAM';
export const GET_ALL_EXAM_SUCCESS = 'GET_ALL_EXAM_SUCCESS';
export const GET_ALL_EXAM_ERROR = 'GET_ALL_EXAM_ERROR';

export const ADD_EXAM = 'ADD_EXAM';
export const ADD_EXAM_SUCCESS = 'ADD_EXAM_SUCCESS';
export const ADD_EXAM_ERROR = 'ADD_EXAM_ERROR';

export const EDIT_EXAM = 'EDIT_EXAM';
export const EDIT_EXAM_SUCCESS = 'EDIT_EXAM_SUCCESS';
export const EDIT_EXAM_ERROR = 'EDIT_EXAM_ERROR';

export const DELETE_EXAM = 'DELETE_EXAM';
export const DELETE_EXAM_SUCCESS = 'DELETE_EXAM_SUCCESS';
export const DELETE_EXAM_ERROR = 'DELETE_EXAM_ERROR';

export const RESET = 'RESET';